env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
  no-unused-vars:
    - error

